sources:
  - name: silver_schema
    schema: 'silver'
    tables:
      - name: fact_claim
        columns:
          - name: claim_id
            tests:
              - unique
              - not_null
              - not_audit_passed
      - name: fact_term