insurance_case: # this needs to match the profile in your dbt_project.yml file
    target: dev
    outputs:
        dev:
            type: duckdb
            path: '../dagster-quickstart/insurance_case.db'

